# This workflow will publish the typescript package to npm on release
# This requires you to have a secret NPM_TOKEN saved in your github environment

name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #  -----  checkout & setup node  -----
      #----------------------------------------------
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        id: setup-node
        with:
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      #---------------------------------------------------------------
      #  -----  install dependencies -----
      #---------------------------------------------------------------
      - name: install dependencies
        run: npm install
      #------------------------------
      #  -----  publish -----
      #------------------------------
      - name: build & publish
        run: |
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
