# This workflow will test the typescript package against Sideko's Mock Servers
# Tests will run automatically on a push to `main` or a pull request event

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #  -----  checkout & setup node  -----
      #----------------------------------------------
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        id: setup-node
        with:
          cache: "npm"
      #---------------------------------------------------------------
      #  -----  install dependencies -----
      #---------------------------------------------------------------
      - name: install dependencies
        run: npm install
      #------------------------------
      #  -----  run tests -----
      #------------------------------
      - name: run jest
        run: npm test
